// <auto-generated />
namespace LocadoraCarros.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Carro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Carro));
        
        string IMigrationMetadata.Id
        {
            get { return "201508261754318_Carro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
